// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDsccwyWLlJ-Odo6Wj5zW_mrcF1V0Y5ds',
    appId: '1:475638086512:web:3423bf9c3f3cd3851eadb5',
    messagingSenderId: '475638086512',
    projectId: 'fcm-app-c5b3f',
    authDomain: 'fcm-app-c5b3f.firebaseapp.com',
    storageBucket: 'fcm-app-c5b3f.firebasestorage.app',
    measurementId: 'G-KYNM3LFTJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuJa-hCk2QhfENZz-RliaX2bdZerkRaDI',
    appId: '1:475638086512:android:42f24b4d8ee235691eadb5',
    messagingSenderId: '475638086512',
    projectId: 'fcm-app-c5b3f',
    storageBucket: 'fcm-app-c5b3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqIcVYoVm9K2qvWT21EpWVUCSjp0IXdCM',
    appId: '1:475638086512:ios:21ec21dc34aff1aa1eadb5',
    messagingSenderId: '475638086512',
    projectId: 'fcm-app-c5b3f',
    storageBucket: 'fcm-app-c5b3f.firebasestorage.app',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDChArRQAEYwmMcK6ELMFZXORQXKCFcNxk',
    appId: '1:58412226753:ios:9e9432ca4da7eeb12d1c40',
    messagingSenderId: '58412226753',
    projectId: 'vibzcheck-4ccd2',
    storageBucket: 'vibzcheck-4ccd2.firebasestorage.app',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe6KZ7ISsDbev0mJOTZPABb_3LVl3ceTM',
    appId: '1:58412226753:web:9eb7b571b4fce5542d1c40',
    messagingSenderId: '58412226753',
    projectId: 'vibzcheck-4ccd2',
    authDomain: 'vibzcheck-4ccd2.firebaseapp.com',
    storageBucket: 'vibzcheck-4ccd2.firebasestorage.app',
    measurementId: 'G-0SE3V0TW1E',
  );

}