// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe6KZ7ISsDbev0mJOTZPABb_3LVl3ceTM',
    appId: '1:58412226753:web:6ce0057280ebb1882d1c40',
    messagingSenderId: '58412226753',
    projectId: 'vibzcheck-4ccd2',
    authDomain: 'vibzcheck-4ccd2.firebaseapp.com',
    storageBucket: 'vibzcheck-4ccd2.firebasestorage.app',
    measurementId: 'G-PVCXWTHKKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-MwLRPA_2gL6oMX4PP79sXp1ODTEGPcw',
    appId: '1:58412226753:android:4aa5dd824f174c9d2d1c40',
    messagingSenderId: '58412226753',
    projectId: 'vibzcheck-4ccd2',
    storageBucket: 'vibzcheck-4ccd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDChArRQAEYwmMcK6ELMFZXORQXKCFcNxk',
    appId: '1:58412226753:ios:9e9432ca4da7eeb12d1c40',
    messagingSenderId: '58412226753',
    projectId: 'vibzcheck-4ccd2',
    storageBucket: 'vibzcheck-4ccd2.firebasestorage.app',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDChArRQAEYwmMcK6ELMFZXORQXKCFcNxk',
    appId: '1:58412226753:ios:9e9432ca4da7eeb12d1c40',
    messagingSenderId: '58412226753',
    projectId: 'vibzcheck-4ccd2',
    storageBucket: 'vibzcheck-4ccd2.firebasestorage.app',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe6KZ7ISsDbev0mJOTZPABb_3LVl3ceTM',
    appId: '1:58412226753:web:9eb7b571b4fce5542d1c40',
    messagingSenderId: '58412226753',
    projectId: 'vibzcheck-4ccd2',
    authDomain: 'vibzcheck-4ccd2.firebaseapp.com',
    storageBucket: 'vibzcheck-4ccd2.firebasestorage.app',
    measurementId: 'G-0SE3V0TW1E',
  );

}